### ISSUE TITLE
`GZ_CONFIG_PATH` shouldn't be set manually

### ISSUE THREAD

**Issue by junwoo091400** [srmainwaring/asv_wave_sim#115]
## Description
In the README, there's this file of the environment setup:

```bash
# ensure gazebo finds the config for this installation
export GZ_CONFIG_PATH=\
$HOME/gz_ws/install/share/gz
```

By running this, I get the following error:
```bash
junwoo@JW-XPS:~/ROS2_ws/asv_wave_ws$ gz sim -v4 -s -r waves.sdf
I cannot find any available 'gz' command:
	* Did you install any Gazebo library?
	* Did you set the GZ_CONFIG_PATH environment variable?
	    E.g.: export GZ_CONFIG_PATH=$HOME/local/share/gz
```

## Suggestion
And this prevents the `gz` command from being found, and the `share/gz` directory doesn't even exist after the colcon build, so I think this step is unnecessary.

What was the reasoning behind this step?

## Notes
Possibly related to: https://github.com/srmainwaring/asv_wave_sim/issues/66

As mentioned here: https://github.com/gazebosim/gz-launch#known-issue-of-command-line-tools, the `GZ_CONFIG_PATH` should point to the location of the `gz` installation, which for my case it was obviously not in the wave sim's location :thinking:

**Comment by srmainwaring** [comment]
Hi @junwoo091400, this is a left-over from the original instructions prior to the release of Gazebo Garden when it needed to be built from source. The instructions suggested that the gz-libs and the wave sim libs were built in the same workspace - and in that case the config location would be present in `.install/share/gz`. I'll update the instructions to remove this step now that Garden is released.
