### ISSUE TITLE
[Err] [SystemLoader.cc:92] Failed to load system plugin [gz-waves1-hydrodynamics-system] : Could not find shared library.

### ISSUE THREAD

**Issue by dlaboy** [srmainwaring/asv_wave_sim#158]
Hello! I'm having problems loading the hydrodynamics plugin, any idea what the problem could be?

**Comment by srmainwaring** [comment]
@dlaboy it’s most likely you have not set up the GZ environment variables correctly, but you will need to provide more information in order to diagnose your problem.

Should include platform, OS version, Gazebo version, output logs from gz sim -v4.

**Comment by dlaboy** [comment]
I'm running it on macOS Sonoma version 14.3.1. Gazebo Harmonic, these are the output logs from gz sim -v4

<img width="1141" alt="Screenshot 2024-02-28 at 11 09 36 PM" src="https://github.com/srmainwaring/asv_wave_sim/assets/89310701/01bcca80-9f00-4565-8dfc-47d745712ba0">

**Comment by dlaboy** [comment]
I apologize, I think I solve this particular problem, colcon build aborted the particular gz-waves1 directory so it wasn't creating install/lib executable files. I'm having another problem know hahah. which I will post next.

**Comment by dlaboy** [comment]
Ones I run gz sim-v4 -s -r catamaran_waves.sdf, this error appears

dlaboy@Diegos-MacBook-Pro ~ % gz sim -v4 -s -r catamaran_waves.sdf
[Msg] Gazebo Sim Server v8.1.0
[Msg] Loading SDF world file[/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/SITL_Models/Gazebo/worlds/catamaran_waves.sdf].
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:860] Loaded [gz::physics::dartsim::Plugin] from library [/opt/homebrew/Cellar/gz-physics7/7.0.0_4/lib/gz-physics-7/engine-plugins/libgz-physics-dartsim-plugin.dylib]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Physics] for entity [1]
[Msg] Create service on [/world/waves/create]
[Msg] Remove service on [/world/waves/remove]
[Msg] Pose service on [/world/waves/set_pose]
[Msg] Pose service on [/world/waves/set_pose_vector]
[Msg] Light configuration service on [/world/waves/light_config]
[Msg] Physics service on [/world/waves/set_physics]
[Msg] SphericalCoordinates service on [/world/waves/set_spherical_coordinates]
[Msg] Enable collision service on [/world/waves/enable_collision]
[Msg] Disable collision service on [/world/waves/disable_collision]
[Msg] Material service on [/world/waves/visual_config]
[Msg] Material service on [/world/waves/wheel_slip]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [Sensors.cc:527] Configuring Sensors system
[Dbg] [Sensors.cc:446] SensorsPrivate::Run
[Dbg] [Sensors.cc:422] SensorsPrivate::RenderThread started
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Sensors] for entity [1]
[Dbg] [Sensors.cc:262] Waiting for init
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Imu] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::NavSat] for entity [1]
[Err] [SystemLoader.cc:92] Failed to load system plugin [asv_sim2-anemometer-system] : Could not find shared library.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1709209400.230898   15253 descriptor_database.cc:633] File already exists in database: gz/msgs/time.proto
F0000 00:00:1709209400.231043   15253 descriptor.cc:2122] Check failed: GeneratedDatabase()->Add(encoded_file_descriptor, size) 
*** Check failure stack trace: ***
    @        0x10090ea7c  absl::lts_20230802::log_internal::LogMessage::SendToLog()
    @        0x10090e580  absl::lts_20230802::log_internal::LogMessage::Flush()
    @        0x10090ed8c  absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x10090eda4  absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x10495516c  google::protobuf::DescriptorPool::InternalAddGeneratedFile()
    @        0x1049d0880  google::protobuf::(anonymous namespace)::AddDescriptors()
    @        0x1049d0868  google::protobuf::(anonymous namespace)::AddDescriptors()
    @        0x1049d0868  google::protobuf::(anonymous namespace)::AddDescriptors()
    @        0x1049d0868  google::protobuf::(anonymous namespace)::AddDescriptors()
    @        0x1049d08b4  google::protobuf::internal::AddDescriptorsRunner::AddDescriptorsRunner()
    @        0x1893f5a24  ___ZZNK5dyld46Loader25findAndRunAllInitializersERNS_12RuntimeStateEENK3$_0clEv_block_invoke
    @        0x18943b0f4  ___ZNK5dyld313MachOAnalyzer18forEachInitializerER11DiagnosticsRKNS0_15VMAddrConverterEU13block_pointerFvjEPKv_block_invoke.202
    @        0x18942e668  ___ZNK5dyld39MachOFile14forEachSectionEU13block_pointerFvRKNS0_11SectionInfoEbRbE_block_invoke
    @        0x1893d52fc  dyld3::MachOFile::forEachLoadCommand()
    @        0x18942d6a0  dyld3::MachOFile::forEachSection()
    @        0x189430188  dyld3::MachOFile::forEachInitializerPointerSection()
    @        0x18943ade8  dyld3::MachOAnalyzer::forEachInitializer()
    @        0x1893f1b38  dyld4::Loader::findAndRunAllInitializers()
    @        0x1893f7f70  dyld4::JustInTimeLoader::runInitializers()
    @        0x1893f1f24  dyld4::Loader::runInitializersBottomUp()
    @        0x1893f1f00  dyld4::Loader::runInitializersBottomUp()
    @        0x1893f1f00  dyld4::Loader::runInitializersBottomUp()
    @        0x1893f1f00  dyld4::Loader::runInitializersBottomUp()
    @        0x1893f5ab0  dyld4::Loader::runInitializersBottomUpPlusUpwardLinks()::$_1::operator()()
    @        0x1893f20f0  dyld4::Loader::runInitializersBottomUpPlusUpwardLinks()
    @        0x1894107ac  dyld4::APIs::dlopen_from()
    @        0x10062e380  gz::plugin::Loader::Implementation::LoadLib()
    @        0x10062e144  gz::plugin::Loader::LoadLib()
    @        0x10109bb74  gz::sim::SystemLoaderPrivate::InstantiateSystemPlugin()
    @        0x10109b758  gz::sim::v8::SystemLoader::LoadPlugin()
    @        0x10109ea68  gz::sim::v8::SystemManager::LoadPlugin()
    @        0x101080210  gz::sim::v8::SimulationRunner::LoadPlugins()
    @        0x101064144  gz::common::EventT<>::Signal<>()
    @        0x10104b0b8  gz::sim::v8::EventManager::Emit<>()
    @        0x101049fa4  gz::sim::v8::SdfEntityCreator::CreateEntities()
    @        0x101014d94  gz::sim::v8::LevelManager::LoadActiveEntities()
    @        0x1010142bc  gz::sim::v8::LevelManager::UpdateLevelsState()
    @        0x10107ebf0  gz::sim::v8::SimulationRunner::SimulationRunner()
    @        0x101076acc  gz::sim::v8::ServerPrivate::CreateEntities()
    @        0x10106f3f4  gz::sim::v8::Server::Server()
    @        0x10046ce44  runServer
    @        0x19a2ef050  ffi_call_SYSV
    @        0x19a2f7adc  ffi_call_int
    @        0x1002d16e8  Init_fiddle_function
    @        0x1fa6d4514  rb_thread_call_without_gvl2
    @        0x1002d1154  Init_fiddle_function
    @        0x1fa70a4b0  rb_vm_fstring_table
    @        0x1fa6f94fc  rb_vm_get_insns_address_table
    @        0x1fa707144  rb_vm_exec
    @        0x1fa5e61d0  ruby_exec_node
    @        0x1fa5e606c  ruby_run_node
    @        0x10027353c  main
    @        0x1893d90e0  start
Stack trace (most recent call last):
#17   Object "libprotobuf.25.3.0.dylib", at 0x1049d08b3, in google::protobuf::internal::AddDescriptorsRunner::AddDescriptorsRunner(google::protobuf::internal::DescriptorTable const*) + 23
#16   Object "libprotobuf.25.3.0.dylib", at 0x1049d0867, in google::protobuf::(anonymous namespace)::AddDescriptors(google::protobuf::internal::DescriptorTable const*) + 103
#15   Object "libprotobuf.25.3.0.dylib", at 0x1049d0867, in google::protobuf::(anonymous namespace)::AddDescriptors(google::protobuf::internal::DescriptorTable const*) + 103
#14   Object "libprotobuf.25.3.0.dylib", at 0x1049d0867, in google::protobuf::(anonymous namespace)::AddDescriptors(google::protobuf::internal::DescriptorTable const*) + 103
#13   Object "libprotobuf.25.3.0.dylib", at 0x1049d087f, in google::protobuf::(anonymous namespace)::AddDescriptors(google::protobuf::internal::DescriptorTable const*) + 127
#12   Object "libprotobuf.25.3.0.dylib", at 0x10495516b, in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) + 127
#11   Object "libabsl_log_internal_message.2308.0", at 0x10090eda3, in absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal() + 11
#10   Object "libabsl_log_internal_message.2308.0", at 0x10090ed8b, in absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal() + 11
#9    Object "libabsl_log_internal_message.2308.0", at 0x10090e57f, in absl::lts_20230802::log_internal::LogMessage::Flush() + 287
#8    Object "libabsl_log_internal_message.2308.0", at 0x10090eacb, in absl::lts_20230802::log_internal::LogMessage::SendToLog() + 127
#7    Object "libabsl_log_internal_message.2308.0", at 0x10090ed4b, in absl::lts_20230802::log_internal::LogMessage::Die() + 35
#6    Object "libabsl_log_internal_message.2308.0", at 0x10090e90f, in absl::lts_20230802::log_internal::LogMessage::FailWithoutStackTrace() + 19
#5    Object "libsystem_c.dylib", at 0x189665a3f, in abort + 179
#4    Object "libsystem_pthread.dylib", at 0x189759cbf, in pthread_kill + 287
#3    Object "libsystem_platform.dylib", at 0x189789a23, in _sigtramp + 55
#2    Object "libgz-tools2-backward.dylib", at 0x100353377, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 19
#1    Object "libgz-tools2-backward.dylib", at 0x1003533db, in backward::SignalHandling::handleSignal(int, __siginfo*, void*) + 71
#0    Object "libgz-tools2-backward.dylib", at 0x10035351b, in backward::StackTraceImpl<backward::system_tag::darwin_tag>::load_from(void*, unsigned long, void*, void*) + 43
zsh: abort      gz sim -v4 -s -r catamaran_waves.sdf

**Comment by dlaboy** [comment]
These are the values for GZ_*

dlaboy@Diegos-MacBook-Pro ~ % env | grep GZ
GZ_SIM_SYSTEM_PLUGIN_PATH=/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/ardupilot_gazebo/build:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/install/lib:
GZ_SIM_RESOURCE_PATH=:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/SITL_Models/Gazebo/models:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/SITL_Models/Gazebo/worlds:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/asv_wave_sim/gz-waves-models/models:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/asv_wave_sim/gz-waves-models/world_models:/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/asv_wave_sim/gz-waves-models/worlds
GZ_VERSION=garden
GZ_GUI_PLUGIN_PATH=$GZ_GUI_PLUGIN_PATH:~/Desktop/college/roboboat_stuff/repos/gz_ws/src/asv_wave_sim/gz-waves/src/gui/plugins/waves_control/build

**Comment by dlaboy** [comment]
Okk I will try this

**Comment by dlaboy** [comment]
1. I'm using a binary installation
2. sensors seem to run well on example for iris_runway.sdf from ardupilot_gazebo. 

dlaboy@Diegos-MBP ~ % gz sim -v4 -s -r iris_runway.sdf
[Msg] Gazebo Sim Server v8.1.0
[Msg] Loading SDF world file[/Users/dlaboy/Desktop/college/roboboat_stuff/repos/gz_ws/src/ardupilot_gazebo/worlds/iris_runway.sdf].
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:860] Loaded [gz::physics::dartsim::Plugin] from library [/opt/homebrew/Cellar/gz-physics7/7.0.0_4/lib/gz-physics-7/engine-plugins/libgz-physics-dartsim-plugin.dylib]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Physics] for entity [1]
[Dbg] [Sensors.cc:527] Configuring Sensors system
[Dbg] [Sensors.cc:446] SensorsPrivate::Run
[Dbg] [Sensors.cc:422] SensorsPrivate::RenderThread started
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Sensors] for entity [1]
[Dbg] [Sensors.cc:262] Waiting for init
[Msg] Create service on [/world/iris_runway/create]
[Msg] Remove service on [/world/iris_runway/remove]
[Msg] Pose service on [/world/iris_runway/set_pose]
[Msg] Pose service on [/world/iris_runway/set_pose_vector]
[Msg] Light configuration service on [/world/iris_runway/light_config]
[Msg] Physics service on [/world/iris_runway/set_physics]
[Msg] SphericalCoordinates service on [/world/iris_runway/set_spherical_coordinates]
[Msg] Enable collision service on [/world/iris_runway/enable_collision]
[Msg] Disable collision service on [/world/iris_runway/disable_collision]
[Msg] Material service on [/world/iris_runway/visual_config]
[Msg] Material service on [/world/iris_runway/wheel_slip]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Imu] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::NavSat] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::JointStatePublisher] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::LiftDrag] for entity [15]
[Msg] ApplyJointForce subscribing to Double messages on [/model/iris_with_ardupilot/joint/iris_with_standoffs::rotor_0_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [15]
[Msg] ApplyJointForce subscribing to Double messages on [/model/iris_with_ardupilot/joint/iris_with_standoffs::rotor_1_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [15]
[Msg] ApplyJointForce subscribing to Double messages on [/model/iris_with_ardupilot/joint/iris_with_standoffs::rotor_2_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [15]
[Msg] ApplyJointForce subscribing to Double messages on [/model/iris_with_ardupilot/joint/iris_with_standoffs::rotor_3_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [15]
[Dbg] [SystemManager.cc:74] Loaded system [ArduPilotPlugin] for entity [15]
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/iris_runway/control], [/world/iris_runway/control/state] and [/world/iris_runway/playback/control]
[Msg] Serving GUI information on [/world/iris_runway/gui/info]
[Msg] World [iris_runway] initialized with [1ms] physics profile.
[Msg] Serving world SDF generation service on [/world/iris_runway/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource path resolve service on [/gazebo/resource_paths/resolve].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:545] Creating PostUpdate worker threads: 7
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (0)
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (1)
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (2)
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (3)
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (4)
[Dbg] [SimulationRunner.cc:556] Creating postupdate worker thread (5)
[Msg] Found IMU sensor with name [iris_with_standoffs::imu_link::imu_sensor]
[Dbg] [ArduPilotPlugin.cc:1156] Computed IMU topic to be: world/iris_runway/model/iris_with_ardupilot/model/iris_with_standoffs/link/imu_link/sensor/imu_sensor/imu
[Dbg] [ImuSensor.cc:150] IMU data for [iris_with_ardupilot::iris_with_standoffs::imu_link::imu_sensor] advertised on [world/iris_runway/model/iris_with_ardupilot/model/iris_with_standoffs/link/imu_link/sensor/imu_sensor/imu]
[Msg] Serving scene information on [/world/iris_runway/scene/info]
[Msg] Serving graph information on [/world/iris_runway/scene/graph]
[Msg] Serving full state on [/world/iris_runway/state]
[Msg] Serving full state (async) on [/world/iris_runway/state_async]
[Msg] Publishing scene information on [/world/iris_runway/scene/info]
[Msg] Publishing entity deletions on [/world/iris_runway/scene/deletion]
[Msg] Publishing state changes on [/world/iris_runway/state]
[Msg] Publishing pose messages on [/world/iris_runway/pose/info]
[Msg] Publishing dynamic pose messages on [/world/iris_runway/dynamic_pose/info]
[Dbg] [EntityComponentManager.cc:1655] Updated state thread iterators: 10 threads processing around 5 entities each.
[Wrn] [Model.hh:69] Skipping serialization / deserialization for models with //pose/@relative_to attribute.
[Wrn] [Component.hh:144] Trying to serialize component with data type [N3sdf3v145WorldE], which doesn't have `operator<<`. Component will not be serialized.

3. I tried this, still same output
