### ISSUE TITLE
Compile Error of package with Colcon

### ISSUE THREAD

**Issue by joao-portela** [srmainwaring/asv_wave_sim#159]
Hi,

I was trying to compile a package following the instructions of the README, but i got a 
[terminal_return.txt](https://github.com/srmainwaring/asv_wave_sim/files/14441089/terminal_return.txt)
compile error when enter this command:
`colcon build --symlink-install --merge-install --cmake-args \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DBUILD_TESTING=ON \
-DCMAKE_CXX_STANDARD=17`

after that i got a bunch of message errors in the terminal (is in the attached file, it was too long...)
[terminal_return.txt](https://github.com/srmainwaring/asv_wave_sim/files/14441098/terminal_return.txt)

I wasnt able to identify where the problem is 
i'll be grateful if anyone can help me with this.

**Comment by srmainwaring** [comment]
@joao-portela, it looks as if your eigen and gz sim libraries are not consistent / up to date. Check that you have run `sudo apt update && sudo apt upgrade`, that you have only one version of `gz sim` installed (either Garden or Harmonic), that you do not have gazebo classic installed as this will clash, and that you have set the environment variable `GZ_VERSION` correctly.
