### ISSUE TITLE
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)

### ISSUE THREAD

**Issue by EricDaJiang** [srmainwaring/asv_wave_sim#162]
Hello! When I run gz sim -v4 -s -r -g waves.sdf, the Gazebo window does not appear, and the following error occurs: 

leojt@Legion-Y7000P:~/usv_simulator/asv_wave_ws/src/asv_wave_sim/gz-waves-models/worlds$ source ~/.bashrc 
not found: "/home/leojt/usv_integrat/install/flash3d_gnss_imu_fusion/share/flash3d_gnss_imu_fusion/local_setup.bash"
not found: "/home/leojt/usv_integrat/install/flash3d_gnss_imu_fusion/share/flash3d_gnss_imu_fusion/local_setup.bash"
leojt@Legion-Y7000P:~/usv_simulator/asv_wave_ws/src/asv_wave_sim/gz-waves-models/worlds$ gz sim -v4 -s -r -g waves.sdf
[Msg] Gazebo Sim Server v7.7.0
[Msg] Loading SDF world file[/home/leojt/usv_simulator/asv_wave_ws/src/asv_wave_sim/gz-waves-models/worlds/waves.sdf].
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:880] Loaded [gz::physics::dartsim::Plugin] from library [/usr/lib/x86_64-linux-gnu/gz-physics-6/engine-plugins/libgz-physics-dartsim-plugin.so]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Physics] for entity [1]
[Dbg] [Sensors.cc:525] Configuring Sensors system
[Dbg] [Sensors.cc:444] SensorsPrivate::Run
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Sensors] for entity [1]
[Dbg] [Sensors.cc:421] SensorsPrivate::RenderThread started
[Dbg] [Sensors.cc:261] Waiting for init
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Msg] Create service on [/world/waves/create]
[Msg] Remove service on [/world/waves/remove]
[Msg] Pose service on [/world/waves/set_pose]
[Msg] Pose service on [/world/waves/set_pose_vector]
[Msg] Light configuration service on [/world/waves/light_config]
[Msg] Physics service on [/world/waves/set_physics]
[Msg] SphericalCoordinates service on [/world/waves/set_spherical_coordinates]
[Msg] Enable collision service on [/world/waves/enable_collision]
[Msg] Disable collision service on [/world/waves/disable_collision]
[Msg] Material service on [/world/waves/visual_config]
[Msg] Material service on [/world/waves/wheel_slip]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Imu] for entity [1]
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::WavesModel]
- Requested library name: [gz-waves1-waves-model-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::WavesVisual]
- Requested library name: [gz-waves1-waves-visual-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::JointStatePublisher] for entity [20]
[Msg] ApplyJointForce subscribing to Double messages on [/model/wam-v/joint/left_engine_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [20]
[Msg] ApplyJointForce subscribing to Double messages on [/model/wam-v/joint/right_engine_joint/cmd_force]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::ApplyJointForce] for entity [20]
[Msg] Thruster listening to commands on [/model/wam-v/joint/left_propeller_joint/cmd_thrust]
[Msg] Thruster listening to enable_deadband on [/model/wam-v/joint/left_propeller_joint/enable_deadband]
[Dbg] [Thruster.cc:496] Using velocity control for propeller joint.
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Thruster] for entity [20]
[Msg] Thruster listening to commands on [/model/wam-v/joint/right_propeller_joint/cmd_thrust]
[Msg] Thruster listening to enable_deadband on [/model/wam-v/joint/right_propeller_joint/enable_deadband]
[Dbg] [Thruster.cc:496] Using velocity control for propeller joint.
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Thruster] for entity [20]
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [ArduPilotPlugin]
- Requested library name: [ArduPilotPlugin]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Err] [SystemLoader.cc:119] Failed to load system plugin: (Reason: Could not find shared library)
- Requested plugin name: [gz::sim::systems::Hydrodynamics]
- Requested library name: [gz-waves1-hydrodynamics-system]
- Library search paths:
  - /home/leojt/.gz/sim/plugins/
  - /usr/lib/x86_64-linux-gnu/gz-sim-7/plugins/
  - /home/leojt/.ignition/gazebo/plugins/
  - /home/leojt/usv_simulator/simulator_ws/install/ros_gz_example_gazebo/lib/ros_gz_example_gazebo/
  - /home/leojt/usv_simulator/simulator_ws/install/lib/ros_gz_example_gazebo/
  - /home/leojt/home/leojt/usv_simulator/simulator_ws/install/lib/
  - /home/leojt/leojt/usv_simulator/asv_wave_ws/install/lib/
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/waves/control], [/world/waves/control/state] and [/world/waves/playback/control]
[Msg] Serving GUI information on [/world/waves/gui/info]
[Msg] World [waves] initialized with [default_physics] physics profile.
[Msg] Serving world SDF generation service on [/world/waves/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource path resolve service on [/gazebo/resource_paths/resolve].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:503] Creating PostUpdate worker threads: 7
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (0)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (1)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (2)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (3)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (4)
[Dbg] [SimulationRunner.cc:514] Creating postupdate worker thread (5)
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
[Dbg] [SDFFeatures.cc:328] Mesh construction from an SDF has not been implemented yet for dartsim. Use AttachMeshShapeFeature to use mesh shapes.
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(1)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(1)]
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(2)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(2)]
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(3)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(3)]
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(4)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(4)]
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(5)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(5)]
Msg [NameManager::issueNewName] (Skeleton::BodyNode | barrage::buoy0) The name [base_link] is a duplicate, so it has been renamed to [base_link(6)]
Msg [NameManager::issueNewName] (Skeleton::N4dart8dynamics9ShapeNodeE | barrage::buoy0) The name [base_link:collision] is a duplicate, so it has been renamed to [base_link:collision(6)]
[Dbg] [ImuSensor.cc:149] IMU data for [wam-v::imu_link::imu_sensor] advertised on [world/waves/model/wam-v/link/imu_link/sensor/imu_sensor/imu]
[Msg] Serving scene information on [/world/waves/scene/info]
[Msg] Serving graph information on [/world/waves/scene/graph]
[Msg] Serving full state on [/world/waves/state]
[Msg] Serving full state (async) on [/world/waves/state_async]
[Msg] Publishing scene information on [/world/waves/scene/info]
[Msg] Publishing entity deletions on [/world/waves/scene/deletion]
[Msg] Publishing state changes on [/world/waves/state]
[Msg] Publishing pose messages on [/world/waves/pose/info]
[Msg] Publishing dynamic pose messages on [/world/waves/dynamic_pose/info].

**Comment by srmainwaring** [comment]
@EricDaJiang, most likely a problem with the system plugin path. If you did not use the `--merge-install` flag when building the libraries will not be under the `<workspace>/install/lib` directory, which you can check by inspection.
